const trackLayoutImage = {
  americas: require('../assets/images/tracks/austin.png'),
  bahrain: require('../assets/images/tracks/bahrain.png'),
  BAK: require('../assets/images/tracks/baku.png'),
  hungaroring: require('../assets/images/tracks/budapest.png'),
  catalunya: require('../assets/images/tracks/catalunya.png'),
  ricard: require('../assets/images/tracks/le_castellet.png'),
  albert_park: require('../assets/images/tracks/melbourne.png'),
  rodriguez: require('../assets/images/tracks/mexico_city.png'),
  monaco: require('../assets/images/tracks/monte_carlo.png'),
  monza: require('../assets/images/tracks/monza.png'),
  interlagos: require('../assets/images/tracks/sao_paulo.png'),
  silverstone: require('../assets/images/tracks/silverstone.png'),
  sochi: require('../assets/images/tracks/sochi.png'),
  spa: require('../assets/images/tracks/spa_francorchamps.png'),
  red_bull_ring: require('../assets/images/tracks/spielberg.png'),
  suzuka: require('../assets/images/tracks/suzuka.png'),
  yas_marina: require('../assets/images/tracks/yas_island.png'),
  jeddah: require('../assets/images/tracks/jeddah.png'),
  istanbul: require('../assets/images/tracks/istanbul.png'),
  zandvoort: require('../assets/images/tracks/zandvoort.png'),
  portimao: require('../assets/images/tracks/portimao.png'),
  imola: require('../assets/images/tracks/imola.png'),
};

const trackFlagImage = {
  americas: require('../assets/images/flags/austin.png'),
  bahrain: require('../assets/images/flags/bahrain.png'),
  BAK: require('../assets/images/flags/baku.png'),
  hungaroring: require('../assets/images/flags/budapest.png'),
  catalunya: require('../assets/images/flags/catalunya.png'),
  ricard: require('../assets/images/flags/le_castellet.png'),
  albert_park: require('../assets/images/flags/melbourne.png'),
  rodriguez: require('../assets/images/flags/mexico_city.png'),
  monaco: require('../assets/images/flags/monte_carlo.png'),
  monza: require('../assets/images/flags/monza.png'),
  interlagos: require('../assets/images/flags/sao_paulo.png'),
  silverstone: require('../assets/images/flags/silverstone.png'),
  sochi: require('../assets/images/flags/sochi.png'),
  spa: require('../assets/images/flags/spa_francorchamps.png'),
  red_bull_ring: require('../assets/images/flags/spielberg.png'),
  suzuka: require('../assets/images/flags/suzuka.png'),
  yas_marina: require('../assets/images/flags/yas_island.png'),
  jeddah: require('../assets/images/flags/jeddah.png'),
  istanbul: require('../assets/images/flags/istanbul.png'),
  zandvoort: require('../assets/images/flags/zandvoort.png'),
  portimao: require('../assets/images/flags/portimao.png'),
  imola: require('../assets/images/flags/imola.png'),
};

const driverProfileImage = {
  alonso: require('../assets/images/drivers/alonso/profile.jpeg'),
  bottas: require('../assets/images/drivers/bottas/profile.jpeg'),
  gasly: require('../assets/images/drivers/gasly/profile.jpeg'),
  giovinazzi: require('../assets/images/drivers/giovinazzi/profile.jpeg'),
  hamilton: require('../assets/images/drivers/hamilton/profile.jpeg'),
  latifi: require('../assets/images/drivers/latifi/profile.jpeg'),
  leclerc: require('../assets/images/drivers/leclerc/profile.jpeg'),
  mazepin: require('../assets/images/drivers/mazepin/profile.jpeg'),
  norris: require('../assets/images/drivers/norris/profile.jpeg'),
  ocon: require('../assets/images/drivers/ocon/profile.jpeg'),
  perez: require('../assets/images/drivers/perez/profile.jpeg'),
  raikkonen: require('../assets/images/drivers/raikkonen/profile.jpeg'),
  ricciardo: require('../assets/images/drivers/ricciardo/profile.jpeg'),
  russell: require('../assets/images/drivers/russell/profile.jpeg'),
  sainz: require('../assets/images/drivers/sainz/profile.jpeg'),
  mick_schumacher: require('../assets/images/drivers/schumacher/profile.jpeg'),
  stroll: require('../assets/images/drivers/stroll/profile.jpeg'),
  tsunoda: require('../assets/images/drivers/tsunoda/profile.jpeg'),
  max_verstappen: require('../assets/images/drivers/verstappen/profile.jpeg'),
  vettel: require('../assets/images/drivers/vettel/profile.jpeg'),
};

const driverHelmetImage = {
  alonso: require('../assets/images/drivers/alonso/helmet.png'),
  bottas: require('../assets/images/drivers/bottas/helmet.png'),
  gasly: require('../assets/images/drivers/gasly/helmet.png'),
  giovinazzi: require('../assets/images/drivers/giovinazzi/helmet.png'),
  hamilton: require('../assets/images/drivers/hamilton/helmet.png'),
  latifi: require('../assets/images/drivers/latifi/helmet.png'),
  leclerc: require('../assets/images/drivers/leclerc/helmet.png'),
  mazepin: require('../assets/images/drivers/mazepin/helmet.png'),
  norris: require('../assets/images/drivers/norris/helmet.png'),
  ocon: require('../assets/images/drivers/ocon/helmet.png'),
  perez: require('../assets/images/drivers/perez/helmet.png'),
  raikkonen: require('../assets/images/drivers/raikkonen/helmet.png'),
  ricciardo: require('../assets/images/drivers/ricciardo/helmet.png'),
  russell: require('../assets/images/drivers/russell/helmet.png'),
  sainz: require('../assets/images/drivers/sainz/helmet.png'),
  mick_schumacher: require('../assets/images/drivers/schumacher/helmet.png'),
  stroll: require('../assets/images/drivers/stroll/helmet.png'),
  tsunoda: require('../assets/images/drivers/tsunoda/helmet.png'),
  max_verstappen: require('../assets/images/drivers/verstappen/helmet.png'),
  vettel: require('../assets/images/drivers/vettel/helmet.png'),
};

const driverNumberImage = {
  alonso: require('../assets/images/drivers/alonso/number.png'),
  bottas: require('../assets/images/drivers/bottas/number.png'),
  gasly: require('../assets/images/drivers/gasly/number.png'),
  giovinazzi: require('../assets/images/drivers/giovinazzi/number.png'),
  hamilton: require('../assets/images/drivers/hamilton/number.png'),
  latifi: require('../assets/images/drivers/latifi/number.png'),
  leclerc: require('../assets/images/drivers/leclerc/number.png'),
  mazepin: require('../assets/images/drivers/mazepin/number.png'),
  norris: require('../assets/images/drivers/norris/number.png'),
  ocon: require('../assets/images/drivers/ocon/number.png'),
  perez: require('../assets/images/drivers/perez/number.png'),
  raikkonen: require('../assets/images/drivers/raikkonen/number.png'),
  ricciardo: require('../assets/images/drivers/ricciardo/number.png'),
  russell: require('../assets/images/drivers/russell/number.png'),
  sainz: require('../assets/images/drivers/sainz/number.png'),
  mick_schumacher: require('../assets/images/drivers/schumacher/number.png'),
  stroll: require('../assets/images/drivers/stroll/number.png'),
  tsunoda: require('../assets/images/drivers/tsunoda/number.png'),
  max_verstappen: require('../assets/images/drivers/verstappen/number.png'),
  vettel: require('../assets/images/drivers/vettel/number.png'),
};

const constructorCarImage = {
  alfa: require('../assets/images/cars/alfaromeo.png'),
  ferrari: require('../assets/images/cars/ferrari.png'),
  haas: require('../assets/images/cars/haas.png'),
  mclaren: require('../assets/images/cars/mclaren.png'),
  mercedes: require('../assets/images/cars/mercedes.png'),
  aston_martin: require('../assets/images/cars/astonmartin.png'),
  red_bull: require('../assets/images/cars/redbull.png'),
  alpine: require('../assets/images/cars/alpine.png'),
  alphatauri: require('../assets/images/cars/alphatauri.png'),
  williams: require('../assets/images/cars/williams.png'),
};

const constructorLogoImage = {
  alfa: require('../assets/images/logo/alfaromeo.png'),
  ferrari: require('../assets/images/logo/ferrari.png'),
  haas: require('../assets/images/logo/haas.png'),
  mclaren: require('../assets/images/logo/mclaren.png'),
  mercedes: require('../assets/images/logo/mercedes.png'),
  aston_martin: require('../assets/images/logo/astonmartin.png'),
  red_bull: require('../assets/images/logo/redbull.png'),
  alpine: require('../assets/images/logo/alpine.png'),
  alphatauri: require('../assets/images/logo/alphatauri.png'),
  williams: require('../assets/images/logo/williams.png'),
};

const NewsImages = {
  shareAltSolid: require('../assets/images/share-alt-solid.png'),
  angleLeft: require('../assets/images/angle-left-solid.png'),
};

export {
  trackLayoutImage,
  trackFlagImage,
  driverProfileImage,
  driverHelmetImage,
  driverNumberImage,
  constructorCarImage,
  constructorLogoImage,
  NewsImages,
};
